# Generated by Django 4.2.23 on 2025-08-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todomodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='tile of duty')),
                ('priority', models.IntegerField(max_length=1, verbose_name='how important?')),
                ('is_done', models.BooleanField(default=0, verbose_name='Finished?')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Todos',
            },
        ),
    ]
